### ISSUE TITLE
App Ready for Review

### ISSUE THREAD

**Issue by baiIey** [baiIey/events-and-states#1]
My app is not complete, but please review. 

I've run into an error with no error code: I've been switching my initial view controllers for this project, and when I aligned the view controller to the top level to create the GIF, I'm no longer seeing my app. Instead, the app builds, the launch screen loads, and I get nothing but a black screen. 

I'm going to try to fix the error, but it may take some time. Here's the offending build that I submitted for review:
https://github.com/baiIey/events-and-states/commit/aa7a7157e91ca97d599e02b1b61f109c921f6e0c

/cc @codepathreview

**Comment by timothy1ee** [comment]
The reason there is a problem is that in your Storyboard, there is actually 2 navigation controllers sitting on top of each other, which I think is confusing you. Try dragging the initial navigation controller around, you'll see there is another one sitting underneath it.

**Comment by baiIey** [comment]
Thank you, good catch. 

I've updated the project and everything is working without issues now.
